import re


def clean_sql(sql: str) -> str:
    """
    Cleans SQL generated by the LLM.
    Removes markdown, extra spaces, and trailing semicolons.
    """

    if not sql:
        return ""

    # Remove markdown code blocks
    sql = sql.replace("```sql", "")
    sql = sql.replace("```", "")

    # Remove leading/trailing whitespace
    sql = sql.strip()

    # Remove trailing semicolon
    sql = sql.rstrip(";")

    # Collapse multiple spaces/newlines
    sql = re.sub(r"\s+", " ", sql)

    return sql